### ISSUE TITLE
XML configuration for extended classes

### ISSUE THREAD

**Issue by CasperDB** [jmapper-framework/jmapper-core#17]
I'm trying to map between two classes, however the desired destination class need to extend another class. Is this possible?

I've asked this question in more detail, [here:](http://stackoverflow.com/questions/32069487/jmapper-xml-configuration-for-extended-classes)

Thanks,
Casper

**Comment by avurro** [comment]
Language is the same class? Or are two classes in different package?

**Comment by CasperDB** [comment]
They are two different classes, same name and different packages yes.

**Comment by avurro** [comment]
You need to map Language soo

**Comment by CasperDB** [comment]
I'm not sure I follow, any chance you could show me what the implementation and config file would look like for the language field only?

**Comment by avurro** [comment]
```xml
<jmapper>
    <class name="package.RequestS">
        <attribute name="language">
            <value name="language"/>
        </attribute>
    </class>
    <class name="package.Language">
        <global />
    </class>
</jmapper>
```

**Comment by CasperDB** [comment]
Unfortunately that didn't work. I still get the same error:
"Caused by: com.googlecode.jmapper.exceptions.UndefinedMappingException: it was not possible to map the mapped language field of the RequestD Class with the language field of RequestS Class,.."

It seems like I'm missing something to extend the Destination class (RequestD) to RequestBase where the variables are declared.

**Comment by avurro** [comment]
try to add the configuration to RequestD as follow:
```xml
<jmapper>
    <class name="package.RequestD">
        <attribute name="language">
            <value name="language"/>
        </attribute>
    </class>
    <class name="package.Language">
        <global />
    </class>
</jmapper>
```
Meanwhile i will investigate on this issue

**Comment by CasperDB** [comment]
I think the answer is to globally map to the destination class, this has worked for me:
```xml
<jmapper>
    <class name="package.RequestD">
        <global/>
    </class>
</jmapper>
```

Thank you for your help!
