### ISSUE TITLE
get the destination mapped field using the source field

### ISSUE THREAD

**Issue by menafawzy** [jmapper-framework/jmapper-core#25]
There are no any APIs for getting the destination mapped field using the source field

**Comment by avurro** [comment]
Hi,
The wiki is in revision phase, however this API permits to define the configuration to give as input to JMapper class.

```java
JMapperAPI api = new JMapperAPI(......);

JMapper<D,S> mapper = new JMapper<>(D.class, S.class, api);
S s = new S();
D d = mapper.getDestination(s);
```
After the JMapper creation, you should call the method [getDestination](https://github.com/jmapper-framework/jmapper-core/wiki/getDestination-method).

This is a third type of configuration, not an alternative to JMapper.

**Comment by menafawzy** [comment]
sorry my issue hasn't enough description.
I was asking for some sort of APIs that takes the source class and the destination class and the desired field in the destination and return the source field that mapped from.

<S, D> String getSourceFieldName(final Class<S> source, final Class<D> destination, final String destinationFieldName);

<S, D> String getDestinationFieldName(final Class<S> source, final Class<D> destination, final String sourceFieldName);

here is my case to need something like that:
in my web app, I use DTO in the view layer and in case of submit i have to validate against the database, then i map it to the entity model to validate, the error contain the property (field) and the validation message, here i need to know which field in the source dto to send with it the message to the view layer.
thanks for your replay

**Comment by avurro** [comment]
What you need is a sort of ConfigurationHelper, that permits to read the configuration at runtime. Right ?
Currently there aren't APIs for this purpose, but is possible apply a workaround:
```java
String getTargetFieldName(final Class<D> configuredClass, final String mappedFieldName){
     // missing try-catch statment
     return configuredClass
                    .getDeclaredField(mappedFieldName)
                    .getAnnotation(JMap.class)
                    .value();
}
```
With the next release we will write a series of utility methods for this scope.

**Comment by menafawzy** [comment]
thanks for your replay and your time.
I already did the workaround that handle the basic using of annotations (JMap and JGlobalMap),
not handle (attributes or classes), nested annotation and xml.

thanks again,
happy to use jmapper framework and waiting for the next release.

**Comment by avurro** [comment]
Thank you for the feedback, 
Add a star to the project if you like it.

Thank you again!
