### ISSUE TITLE
Mapping from class derived from Template to POJO

### ISSUE THREAD

**Issue by blacksmith77** [jmapper-framework/jmapper-core#30]
Ciao Alessandro,

    I attach a tester using JMapper v1.6.0 that solicitate an exception when object of a class that specify a template class is mappet to a POJO of a simple class

In this case Boddy is User<Integer>

> Exception in thread "Thread-0" com.googlecode.jmapper.exceptions.JMapperException: com.googlecode.jmapper.exceptions.UndefinedMappingException: it was not possible to map the mapped id field of the BuddyVO Class with the id field of Buddy Class, please check the configuration
> 	at com.googlecode.jmapper.config.JmapperLog.ERROR(JmapperLog.java:46)
> 	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:445)
> 	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:372)
> 	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:359)
> 	at com.blacksmithcrew.jmappertester.BuddyVOConverter.mergeBOtoVO(BuddyVOConverter.java:64)
> 	at com.blacksmithcrew.jmappertester.BuddyVOConverter.convertBOtoVO(BuddyVOConverter.java:51)
> 	at com.blacksmithcrew.jmappertester.JMapperTester.run(JMapperTester.java:27)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: com.googlecode.jmapper.exceptions.UndefinedMappingException: it was not possible to map the mapped id field of the BuddyVO Class with the id field of Buddy Class, please check the configuration
> 	at com.googlecode.jmapper.config.Error.undefinedMapping(Error.java:318)
> 	at com.googlecode.jmapper.operations.OperationHandler.loadStructures(OperationHandler.java:168)
> 	at com.googlecode.jmapper.generation.MapperConstructor.<init>(MapperConstructor.java:257)
> 	at com.googlecode.jmapper.generation.MapperBuilder.generate(MapperBuilder.java:84)
> 	at com.googlecode.jmapper.JMapper.createMapper(JMapper.java:458)
> 	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:440)
> 	... 6 more
>  

Thanl for help!
[JMapperTester.jar.zip](https://github.com/jmapper-framework/jmapper-core/files/206114/JMapperTester.jar.zip)

**Comment by avurro** [comment]
I will see as soon as possible, however the `serialVersionUID` field is automatically skipped, it isn't necessary define it in the configuration.

**Comment by avurro** [comment]
It works when the inherited classes belong to the mapped class, fails in case of target class. i'm going to fix it, thank you again

**Comment by avurro** [comment]
Fixed! you will see this fix in the next release.
