### ISSUE TITLE
ConversionBodyIllegalCodeException during usage conversions through JMapperAPI

### ISSUE THREAD

**Issue by aitov** [jmapper-framework/jmapper-core#33]
Hi,
I'm trying use conversation through JMapperAPI:

```java
final JMapperAPI api = new JMapperAPI().add(mappedClass(DTO1.class)
                .add(attribute("fieldX").value("fieldNestedList"))
                .add(conversion("conversion1")
                        .from("fieldNestedList")
                        .to("fieldX")
                        .body("return ${source}.get(0).getFieldY();")));
```

but got exception during excecution:

```
com.googlecode.jmapper.exceptions.JMapperException: com.googlecode.jmapper.exceptions.ConversionBodyIllegalCodeException: the conversion1 method contains illegal code, check the conversion code belonging to the DTO1 class. Additional information: [source error] syntax error near "UTF-8\"?>
<jmapper
 "

	at com.googlecode.jmapper.config.JmapperLog.ERROR(JmapperLog.java:46)
	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:445)
	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:411)
	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:385)
```

root cause at :
[ConversionHandler.java#L164](https://github.com/jmapper-framework/jmapper-core/blob/master/JMapper%20Framework/src/main/java/com/googlecode/jmapper/conversions/explicit/ConversionHandler.java#L164)

beacuse xml.getXmlPath() in this case is full xml (not path to configuration)

Thanks

**Comment by aitov** [comment]
Hi,  
One more question, to avoid this conversion do you plan add support mapping expression like ${fieldNestedList[0].fieldY} ?

**Comment by avurro** [comment]
Hi @aitov ,

Thank you for reporting.
I will solve the problem as soon as possible. 
Your proposal is interesting, I was already thinking of enriching the nested mapping with some function, JMapper will provide a similar functionality in the future.

**Comment by avurro** [comment]
In the meantime add a star to the project if you like :)

**Comment by avurro** [comment]
I have tested your configuration and i have another error:
`JMapper ConversionBodyIllegalCodeException: the conversion1 method contains illegal code, check the conversion code belonging to the DTO1 class. Additional information: [source error] getFieldY() not found in java.lang.Object`
 below the classes used for this test:
```java
public class DTO1 {

	private String fieldX;

	// getter and setter
}

public class DTO2 {

	private List<DTONested> fieldNestedList;

        // getter and setter
}

public class DTONested {

	private String fieldY;

        // getter and setter	
}
```
To solve this problem just make the cast in the body of the conversion:
```java
final JMapperAPI api = new JMapperAPI().add(mappedClass(DTO1.class)
                .add(attribute("fieldX").value("fieldNestedList"))
                .add(conversion("conversion1")
                        .from("fieldNestedList")
                        .to("fieldX")
                        .body("return ((package.DTONested)${source}.get(0)).getFieldY();")));
```
However I have not been able to create your issue, can you give me more information?

**Comment by aitov** [comment]
Hi, 
I'm using 1.6.0 version from maven repository, maybe it is already fixed. Need try with current version

**Comment by aitov** [comment]
Hi,  it works in 1.6.0.1 :) 
When will it be released?

**Comment by avurro** [comment]
Hi @aitov,

I have not made any changes about your report, it's just a configuration error.
In the conversion methods you are subject to bytecode generator limits, in this case Javassist [limits](http://jboss-javassist.github.io/javassist/tutorial/tutorial2.html#limit).

About your proposal will be analyzed and planned.

Thank you for your support

**Comment by aitov** [comment]
Hi,
Just tested with new version from maven - working! :) thanks.
