### ISSUE TITLE
Support of immutable objects

### ISSUE THREAD

**Issue by vraptorche** [jmapper-framework/jmapper-core#37]
When using immutable objects - eg. immutables.org framework, default constructor is missing or private, which prevents instantiation of destination bean

**Comment by avurro** [comment]
Hi,
you have need that the mapping is done through the constructor, or you just need to instantiate destination before mapping?
if it is the second, you can use the `getDestination` method passing the target bean created.
wiki page [here](https://github.com/jmapper-framework/jmapper-core/wiki/getDestination-method#enrichment-signatures).

Add a star if you like the project, thank you in advance!

**Comment by vraptorche** [comment]
Hi,
Thank You for the prompt replay.

I can not use the getDestination() methods because I get exception when I
try to create mapper as per:

JMapper<JobListingVO, JobListingEntity> mapper = new
JMapper<>(JobListingVO.class, JobListingEntity.class);

JobListingVO does not have public default constructor and instances
are created with JobListingVO.create()


Best


~Emil





Dipl. Eng. Emil Korladinov M.Sc. EE
JurassicWare Ltd

http://www.automobilnik.com

**Comment by avurro** [comment]
ok I've seen, but answer my question, what is the desired behavior?

**Comment by vraptorche** [comment]
Hi,
It will be enough to use pre-created instance through getDestination()

Best
~Emil

**Comment by avurro** [comment]
ok, in the next release we will also this feature.

remember to add the star :)

**Comment by avurro** [comment]
Implemented, i'm near to release this feature. stay tuned!
