### ISSUE TITLE
System.out.println in code 

### ISSUE THREAD

**Issue by faroukelabady** [jmapper-framework/jmapper-core#39]
Dear 
I foudn the console have a lot of empty lines after little investigation I found the following code

public class BasicOperation extends ASimpleOperation{

	public StringBuilder mapping() {

		System.out.println("");
		Object content = setDestination(applyImplicitConversion(info.getConversionType(), destinationType(), sourceType(), getSource()));
				           
		// add and return a mapping type control
		return this.addMappingTypeControl(write(content,newLine));
						
	}
	
}

there is a system.out.println() in the code.

**Comment by avurro** [comment]
Fixed, thanks!

**Comment by avurro** [comment]
If you like the project add a star! :)

**Comment by faroukelabady** [comment]
I truly love the project , I also got some ideas while we started using it , maybe we can talk it over, and see if it can be applied or not
