### ISSUE TITLE
Feature-request: Allow optional values for nested mapping if nested attribute is null

### ISSUE THREAD

**Issue by acron17** [jmapper-framework/jmapper-core#41]
I would like to use a nested mapping as follows:
```
<attribute name="something">
  <value name="${some.thing}" />
</attribute>
```
This normally works but crashes when the nested attribute "some" is null. 
I would like to be able to mark this kind of nested mapping optional (maybe giving a default value if the nesting contains a null value).

Maybe like this
```
<attribute name="something">
  <value name="${some.thing}" defaultValue="" />
</attribute>
```

A possible (working) workaround is:
```
<attribute name="something">
  <value name="${some}" />
</attribute>
<conversion name="nullIsEmptySting" to="something">
  return ${source} == null ? "null" : ${source}.getThing(); 
</conversion>
```
but that is annoying to write for all optional attributes. 

Edit: Forgot to mention: Thanks for your work! I really enjoy using JMapper in my project!

**Comment by avurro** [comment]
Hi,

thank you for support!
Your proposal is interesting, in this case to find a solution is important search between existing standards.<br>I think that an Elvis operator is the best response for this need, for example:
```xml
<attribute name="something">
  <value name="${some?.thing}" />
</attribute>
```
as for Elvis operator, if one of variables is null, destination will be null.<br>What you think about?

**Comment by acron17** [comment]
Hi avurro,

thanks for the quick response!
I like your approach to check for existing standards first. However I am not sure if this is the best of all solutions as it doesn't give users the option to chose their own default value (like an empty string in my case). This is inconvenient to me but will give users **real** trouble who have primitive attributes in their target objects.

For my personal issue I think I could live with null values in the target object (I am aiming for some datastructure mapping between different database structures), as I think I could insert the null values into the db instead of empty strings. I however would favor a solution with the mentioned flexibility.

Kind regards acron

**Comment by avurro** [comment]
Default values are a second feature that will be implemented, because it is useful.
For this proposal, i think that a solution may be:
```java
private class Destination{

     @JMap("${some?.thing}") 
     private String field = ""; // default value

    // getter and setter..
}

```
mapping code:
```java
JMapper<Destination, Source> = mapper<>(Destination.class, Source.class);
Source source = new Source();
mapper.getDestination(source, MappingType.ONLY_VALUED_FIELDS);
```
In this case if source is null, destination field will not change. Or in case of enrichment:
```java
mapper.getDestination(destination, source, MappingType.ONLY_VALUED_FIELDS);
```
It's a viable solution for you?

**Comment by acron17** [comment]
Thanks again for your quick response!

> It's a viable solution for you?

Honestly I don't know yet. I don't can set the default value in the way you suggest, as the target classes are generated. Maybe the Java default values (null for objects, 0 and similar for primitive types) will suffices, maybe not. (See below for details on what I actually am trying to achieve). 

Boring(?) details:
My (maybe somewhat special) use case is as follows: 
I want to generate two different sets of classes from two distinct database structures. I than want to use a mapping framework (JMapper ;-) ) to map from objects from the first datastructre to the objects of the second one. As the classes are generated from the tables in a DB I want to configure the whole mapping in XML as these files won't be overwritten when re-generating the classes (which already works... although I am at a pretty early stage of the project).

**Comment by avurro** [comment]
In this case a combination of Elvis operator and default value is for you.
In the middle time, have you need a workaround?

**Comment by acron17** [comment]
Again (at least for me)  being able to set the default value through JMapper would be more convenient as I most likely won't be able to generate the target classes with custom default values (e.g. "" instead of null for strings).

Thanks for asking, no I don't need a workaround. I however would be happy to (alpha/beta) test your implementation against my use case. Just give me the word if you like.

**Comment by avurro** [comment]
I am going to implement the functions mentioned above, after a some study, i will decide if include this features with this release or not (giving priority to default values).
The next comment will be to share the release date.

Your interest is really appreciated, thank you!

**Comment by vash95** [comment]
Hi, i need a workaround, or elvis operation is now work?
