### ISSUE TITLE
System.out.println(""); in com.googlecode.jmapper.operations.simple.BasicOperation

### ISSUE THREAD

**Issue by doctorxavier** [jmapper-framework/jmapper-core#44]
This system.out prints lots of empty lines in log when the application is loaded.

public class BasicOperation extends ASimpleOperation{

	public StringBuilder mapping() {

		System.out.println("");
		Object content = setDestination(applyImplicitConversion(info.getConversionType(), destinationType(), sourceType(), getSource()));
				           
		// add and return a mapping type control
		return this.addMappingTypeControl(write(content,newLine));
						
	}
	
}

**Comment by avurro** [comment]
This is closed in #39 issue.
Anyway thanks for this report, add a star to the project if you like it :)
