### ISSUE TITLE
[Question] Map object to list of objects

### ISSUE THREAD

**Issue by petromir** [jmapper-framework/jmapper-core#45]
I have the following case:
```java
public class RegionEntity {
	private Long id;
	private String name;
}

public class RegionDto {
	private Long id;
	private String name;
}

public class RegionLegalValueDto {
	List<RegionDto> regions;
}
```
So, I want to map `RegionEntity` to a list of `RegionDto` in `RegionLegalValueDto`.

Is there an easy way to achieve that or I should map `RegionEntity` to `RegionDto` first and then put them into the list?

**Comment by avurro** [comment]
No easy wan @petromir, the second proposal is the solution

**Comment by petromir** [comment]
Got it.
