### ISSUE TITLE
[Question] Conversion logic to map few fields to one

### ISSUE THREAD

**Issue by petromir** [jmapper-framework/jmapper-core#46]
I have the following case:
```java
public class UserEntity {
	private Long userId;
	private String username;
	private String firstName;
	private String lastName;
}

public class UserDto {
	private Long id;
	private String name;
}
```
I want to map `username`, `firstName` and `lastName` fields of `UserEntity` to `name` field of `UserDto` by applying some conversion logic. For example:
```java
if (firstName == null || lastName == null) {
	return username // And this will be mapped to 'name' field in UserDto
}
```
How this can be achievied with JMapper? I tried `@JMapConversion`, but it looks like it has different purpose.

**Comment by avurro** [comment]
Mapping is always between two fields in all cases, therefore, it is currently not possible to make the mapping you want, however, is a feature on which I could work.

Thank you! (add a star if you like the project)

**Comment by petromir** [comment]
It would be nice if you develop it as a new feature.
