### ISSUE TITLE
Direct output to System.out stream

### ISSUE THREAD

**Issue by xCASx** [jmapper-framework/jmapper-core#48]
There are a `System.out.println` instruction in `com.googlecode.jmapper.operations.simple.BasicOperation#mapping` method.
This leads to lots of empty strings in output stream on mapper initialisation stage.
It's definitely not a good behaviour for a third party library.

**Comment by avurro** [comment]
Hi @xCASx , this is a bug already fixed, give me the time to release the 1.6.1.CR1 version.

**Comment by xCASx** [comment]
Ok, thank you!

**Comment by avurro** [comment]
give me max two days

**Comment by avurro** [comment]
Fixed!
