### ISSUE TITLE
API conversion for multiple fields doesn't work

### ISSUE THREAD

**Issue by Khinsu** [jmapper-framework/jmapper-core#50]
//broken 
.add(conversion("fromDoubleToString").from("latd", "lgtd").body("..."))

//works
 .add(conversion("fromDoubleToString").from("latd,lgtd").body("..."))

off-by-one error in:
String com.googlecode.jmapper.util.GeneralUtility.join(String charSeparator, String... strings)

**Comment by avurro** [comment]
Hi @Khinsu,

It will be fixed in the next release.

thank you for the support :thumbsup:

**Comment by avurro** [comment]
Fixed and released! :thumbsup:
