### ISSUE TITLE
Flatten and Encapsulate with API

### ISSUE THREAD

**Issue by andreabertagnolli** [jmapper-framework/jmapper-core#52]
Hi, I tried, based on wiki page https://github.com/jmapper-framework/jmapper-core/wiki/Flatten-And-Encapsulate to replicate the encapsulate to flatten example with API but I wasn't able to do it.

There's possibility to see an example?

**Comment by avurro** [comment]
Hi @andreabertagnolli,
Flatten and encapsulate wiki page show how to apply a basic mapping without more configurations, if you need to see how to apply nested mapping visit the [Nested Mapping](https://github.com/jmapper-framework/jmapper-core/wiki/Nested-Mapping) page
