### ISSUE TITLE
[Question] Map when nested objects are null.

### ISSUE THREAD

**Issue by petromir** [jmapper-framework/jmapper-core#53]
I have the following case:
```java
public class Source {
   private String sourceText;
   private NestedSource nestedSource;

   // Getters and Setters
}

public class NestedSource {
   private String nestedSourceData;

   // Getters and Setters
}

public class Destination {
   @JMap(value = "sourceText", classes = Source.class))
   private String destinationText;
   @JMap(value = "${nestedSource.nestedSourceData}", classes = Source.class))
   private String nestedSourceData;

   // Getters and Setters
}

Source source = new Source();
source.setSourceText("Source Text");

JMapper<Destination, Source> mapper = new JMapper<>(Destination.class, Source.class);
Destination destination = mapper.getDestination(dto, NullPointerControl.ALL, MappingType.ONLY_VALUED_FIELDS);
```
The example above doesn't work due to:
```
com.googlecode.jmapper.exceptions.JMapperException:
com.googlecode.jmapper.exceptions.NestedBeanNullException: the field lossOrDamage is null,
   error occured in mapping phase between the fields: RegisterInsuranceClaimEntity.description
   and RegisterInsuranceClaimDto.description
```
Is there a way to get `null` into `nestedSourceData`? I thought that NullPointerControl works even for nested objects.

**Comment by petromir** [comment]
I think #43 might solve the issue.

**Comment by avurro** [comment]
you understand perfectly, this feature will be introduced with the next release, in the meantime you need to implement a conversion

**Comment by petromir** [comment]
...or just to create empty `NestedSource`
Could please you write an example with conversion?

**Comment by avurro** [comment]
An empty NestedSource solve this issue, but if you want more control a conversion method is needed:
```java
@JMapConversion(from={"sourceField"}, to={"destinationField"})
public DestinationType conversion(SouceType sourceField){
             //logic here
             return destinationField;
}
```
I have to review the behavior of conversions in case of nested mapping, i will tell you more in a few hours

**Comment by avurro** [comment]
Hi @petromir,

In case of conversion between nested fields, in `from` and `to` attributes  you must specify only the final field names, for more info see [Explicit conversions](https://github.com/jmapper-framework/jmapper-core/wiki/Explicit-Conversions) wiki page.
