### ISSUE TITLE
MappingType lost in recursive mapping

### ISSUE THREAD

**Issue by petromir** [jmapper-framework/jmapper-core#56]
I have the following case:
```java
public class Source {
	private String sourceText;
	private NestedSource nestedSource;
 
	// Getters, Setters and toString()
}

public class NestedSource {
	private String nestedSourceText;

	// Getters, Setters and toString()
}
public class Destination {
	@JMap(value = "sourceText", classes = Source.class)
	private String destinationText;
	@JMap(value = "nestedSource", classes = Source.class)
	private NestedDestination nestedDestination;

	// Getters, Setters and toString()
}

public class NestedDestination {
	@JMap(value = "nestedSourceText", classes = NestedSource.class)
	private String nestedDestinationText = "Default Destination Text";
        
	// Getters, Setters and toString()
}

final Source source = new Source();
source.setSourceText("Source text");
source.setNestedSource(new NestedSource());
System.out.println(source);
final JMapper<Destination, Source> mapper = new JMapper<Destination, Source>(Destination.class, Source.class);
final Destination destination = mapper.getDestination(source, NullPointerControl.ALL, MappingType.ONLY_VALUED_FIELDS);
System.out.println(destination);
```
And the output is the following:
```java
Source{sourceText='Source text', nestedSource=NestedSource{nestedSourceText='null'}}
Destination{destinationText='Source text', nestedDestination=NestedDestination{nestedDestinationText='null'}}
```
As you can see `nestedDestinationText`'s value has been deleted even if `MappingType.ONLY_VALUED_FIELDS` is selected. Not that this happens only in nested objects, so if you leave `sourceText` as `null`and populate `destinationText` with some value, then the value will be presented, e.g.
```java
Source{sourceText='null', nestedSource=NestedSource{nestedSourceText='null'}}
Destination{destinationText='Default Destination Text', nestedDestination=NestedDestination{nestedDestinationText='null'}}
```

**Comment by avurro** [comment]
Hi @petromir,

this is a bug that i'm going to fix, for now you can proceed? or you're stuck?

**Comment by petromir** [comment]
I'm currently blocked, but I will be happy if you suggest any temporary workaround.

**Comment by avurro** [comment]
you can change the setNestedDestinationText  method? in the case of it:
```java
public void setNestedDestinationText (String nestedDestinationText){
   if(nestedDestinationText != null)
       this.nestedDestinationText = nestedDestinationText;
}
```

**Comment by avurro** [comment]
However this is a recursive mapping, for _nested mapping_ i mean when you need to map a field with another field in different level, an example of nested mapping using your code is:
```java
public class Source {
    @Jmap("{nestedDestination.nestedDestinationText }")
    private String sourceText;
    private NestedSource nestedSource;

    // Getters, Setters and toString()
}
```
for recursive mapping the problem should not exist, I will try to fix as soon as possible

**Comment by petromir** [comment]
We use [lombok](https://projectlombok.org/) to avoid boilerplate code, although I can change that until you fix the issue.
Your second example is not our case, but I'm aware of that functionality and also waiting for resolution of #42

**Comment by avurro** [comment]
ok @petromir! issue fixed! download the project and run: `mvn package` to get the jar with this fix.
Replace the current one with this generated. 
The 1.6.1.CR2 version will be released shortly! stay tuned! :thumbsup:

**Comment by petromir** [comment]
Thanks!
