### ISSUE TITLE
Upload snapshots to public repo.

### ISSUE THREAD

**Issue by petromir** [jmapper-framework/jmapper-core#58]
I would like to use the latest shapshots of JMapper in our projects, so I don't have to wait for full completion of some milestone (_**1.6.1.CR2**_) in order to use alredy fixed issues like https://github.com/jmapper-framework/jmapper-core/issues/56.
I'm aware that snapshot is not a stable version, but at least I will have an option to use what has been done so far immediately.
You can take **_Spring_** approach as an example.

**Comment by avurro** [comment]
ok @petromir, tonight i will release the snapshot that you need :+1: 
In the meantime you are using the jar with the change, as i have advised you?

**Comment by petromir** [comment]
Local jar has some drawbacks when you work in a team of several developers or using a CI tool.
I don't mind to wait for a shapshot repository that you will provide.

**Comment by avurro** [comment]
**1.6.2-SNAPSHOT** released!
```xml
<dependency>
  <groupId>com.googlecode.jmapper-framework</groupId>
  <artifactId>jmapper-core</artifactId>
  <version>1.6.2-SNAPSHOT</version>
</dependency>
```
good work! 👍

**Comment by petromir** [comment]
Great! I still don't see it in Maven Central.

**Comment by avurro** [comment]
you must add the repository in settings.xml:
```xml
<profiles>
  <profile>
     <id>allow-snapshots</id>
        <activation><activeByDefault>true</activeByDefault></activation>
     <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
   </profile>
</profiles>
```

**Comment by petromir** [comment]
Thanks. I'm using Gradle (unfortunately) and I had to do the following:
```javascript
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
