### ISSUE TITLE
convert primitiv to enum class

### ISSUE THREAD

**Issue by ls3642** [jmapper-framework/jmapper-core#59]
**ConversionBodyIllegalCodeException: error in static conversion: probably is an incompatibility of signature, the expected input fields do not match with the real ones, checks the configured class.**

I want to convert a primitiv short to an enum object.

`.add(attribute("anEnum")
                                .value("aShort"))
                        .add(conversion("shortToEnum")
                                .from("aShort").to("anEnum")
                                .type(JMapConversion.Type.DYNAMIC)
                                .body("return com.test.v1.Enum.get(${source});")));`

The class has a get() method which returns an Enum.

```java
public enum Enum {

    NUMBER(1);

    private final int value;

    Enum(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static Enum get(short s){
        for(Enum e: values()){
            if(e.getValue() == s){
                return e;
            }
        }
        return null;
    }
}
```

maybe a Bug?

**Comment by avurro** [comment]
Hi @ls3642,
I will write the test and give you feedback as soon as possible

**Comment by avurro** [comment]
Fixed!
```xml
<dependency>
  <groupId>com.googlecode.jmapper-framework</groupId>
  <artifactId>jmapper-core</artifactId>
  <version>1.6.1.CR2-SNAPSHOT</version>
</dependency>
```
You need to add the Snapshot repository! go to [wiki page](https://github.com/jmapper-framework/jmapper-core/wiki/SNAPSHOT) for this.

Add a star if you like the project! thank you for support! 👍

**Comment by petromir** [comment]
#58 points 1.6.2-SNAPSHOT as a snapshot version. How 1.6.1.CR2-SNAPSHOT differs from it?

**Comment by avurro** [comment]
This snapshot includes several issue, see [release notes](https://github.com/jmapper-framework/jmapper-core/wiki/Release-Notes) for more info. For the first snapshot i haven't reasoned much about the definition of the name. This release include 1.6.2-SNAPSHOT, so you can use it without problem.

**Comment by ls3642** [comment]
Hi @avurro thanks for the fast response!
I do get a Exception: **com.googlecode.jmapper.exceptions.JMapperException: com.googlecode.jmapper.exceptions.ConversionBodyIllegalCodeException: There is an error in the generated method. Additional information: [source error] invalid types for !=**

**Comment by avurro** [comment]
are you using the snapshot?

**Comment by ls3642** [comment]
I thought the snapshot version 1.6.2-SNAPSHOT also includes the fix of this bug. I used now the version 1.6.1.CR2-SNAPSHOT and it worked perfectly. 
Thank you for your support!

**Comment by avurro** [comment]
add a star if you like the project! thank you! :+1:

**Comment by phil-schneider** [comment]
We have the same issue.
Could you create a new release for 1.6.1.CR2-SNAPSHOT
We can not really work with Snapshot versions and I dont want to fork your whole project :-)
Thanks a lot

**Comment by avurro** [comment]
I think about it a bit, let you know

**Comment by petromir** [comment]
I also vote for more often final releases, even if they contain 1 or 2 fixed issues. Thanks for your hard work.

**Comment by phil-schneider** [comment]
Hello,
I cloned the repository to make a local release for 1.6.1.CR2-SNAPSHOT.
But I did not find any commit for this issue, nor did I found any tags or branches for this.
Could you please push your changes?

I understand that you might dont want to release yet, but please give us the chance to release a local version ourself with the fix.
Thanks a lot.

**Comment by avurro** [comment]
@phil-schneider give me the time to release a version with this fix, just few hours.

**Comment by avurro** [comment]
I'm having problems with the tests, I am sorry for the delay

**Comment by avurro** [comment]
Ok guys, 1.6.1.CR2 released! i'm apologize for my delay
