### ISSUE TITLE
map Enum class to same Enum class

### ISSUE THREAD

**Issue by ls3642** [jmapper-framework/jmapper-core#61]
Hi! 
 I would like to map an enum class to the same enum class but i get an exception:

.add(attribute("dogEnum").value("otherDogEnum"))

> JMapperException: java.lang.IllegalArgumentException: No enum constant 

If I  add an conversation like this it does work:
```
.add(conversion("otherDogEnumToDogEnum")
                                .from("otherDogEnum").to("dogEnum")
                                .type(JMapConversion.Type.DYNAMIC)
                                .body("return ${source};"))
```

**Comment by avurro** [comment]
Hi @ls3642 ,
Just the time to create a test and fix it, give me few hours

**Comment by avurro** [comment]
I haven't any error, are you sure that Enum is the same ? can you provide complete code ?
