### ISSUE TITLE
Maven Dependency for Jmapper

### ISSUE THREAD

**Issue by ankuragrwl** [jmapper-framework/jmapper-core#62]
I am looking for the maven dependency for this library. I want to use it in my project.

**Comment by avurro** [comment]
```xml
<dependency>
    <groupId>com.googlecode.jmapper-framework</groupId>
    <artifactId>jmapper-core</artifactId>
    <version>1.6.1.CR2</version>
</dependency>
```
:+1:

**Comment by ankuragrwl** [comment]
Thanks a lot.

I suggest you to add this to readme file.

**Comment by avurro** [comment]
there is a badge "maven central" under **JMapper Framework** title :wink:
