### ISSUE TITLE
No setter/getter for field mapping

### ISSUE THREAD

**Issue by tokazio** [jmapper-framework/jmapper-core#71]
How to map field when it doesn't have a getter/setter ?

Source
```
private Long id;

public Long getId() {
    return id;
}

public void setId(final Long id) {
    this.id = id;
}
```

Destination
```
@JMap
private Long id;
```

Got:

> com.googlecode.jmapper.exceptions.MalformedBeanException: setId method not found in NFGrandTotalPeriode Class for the id field, checks the signature.

**Comment by avurro** [comment]
Hi @tokazio,

Setter and getter methods are required, but you can apply a workaround using [custom accessor methods](https://github.com/jmapper-framework/jmapper-core/wiki/Custom-Accessor-methods).

**Comment by tokazio** [comment]
Yes i'm aware of that. But i'm searching for an automatic field setting system.
I don't want the object (DTO) to expose setters or i want to choose the public ones. But private setters aren't automatically detected too.
